# Generated by Django 5.0.4 on 2024-04-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Блюдо'),
        ),
    ]
